### ISSUE TITLE
Problem with Exit and TEB reporting?

### ISSUE THREAD

**Issue by frnmz** [erick2307/TUNAMI-EVAC1#2]
Hi Thanks for the model!
The model works as intended. But I think there's something wrong with the Exit and TEB reporting.
In the video ([see here](https://streamable.com/u87k86)) we can see that most agents run to the westernmost Exit of the region.
That Exit is supposed to be Exit#1 but as seen in the screenshot below, The Exit#1 monitoring box reports only 4 agents run to it instead.
![Model_0_K4200](https://user-images.githubusercontent.com/18339774/172649680-7db66eb4-0724-47ae-9ee3-40b1475b962f.png)
Is there any documents that explain how Exit and TEB data are identified? Is it only read the "Id" field in the .shp files?

**Comment by erick2307** [comment]
In the `load-spatial` function: `set exit-patches patches gis:intersecting exit-dataset` brings exit point features to the corresponding patch based on the spatial location. Even if the import behavior is ordered by FID, which I am not 100% sure about, the later line of `ask exit-patches [ sprout 1 ... ` will not necessarily sprout exit turtles in the same order as the FID.  
**Then, your Exit#1 in a shp file is not necessarily the same in the NetLogo model.**

My suggestion is:
(1) You may print `teb-capacity` and `exit-capacity` near the end of the `load-spatial` function to verify the location of your exits and the order in the list. Exit#1 corresponds to the first item in the `exit-capacity` list.
(2) Build your monitoring boxes following the order shown by the `exit-capacity` and `teb-capacity` lists.
